version: '2'
services:

  ldapserver:
    image: 'prestodb/centos6-oj8-openldap:${DOCKER_IMAGES_VERSION}'

  presto-master:
    domainname: docker.cluster
    hostname: presto-master
    image: 'prestodb/centos6-oj8-openldap:${DOCKER_IMAGES_VERSION}'
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh multinode-tls-ldap-master run
    extra_hosts:
       - "${LDAP_SERVER_HOST}:${LDAP_SERVER_IP}"
    ports:
      - '7778:7778'
    networks:
      default:
        aliases:
         - presto-master.docker.cluster
    depends_on:
      - ldapserver
    volumes:
      - ../../../conf/presto/etc/multinode-ldap-authenticator.properties:/docker/volumes/conf/presto/etc/password-authenticator.properties

  presto-worker-1:
    domainname: docker.cluster
    hostname: presto-worker-1
    extends:
      file: ../common/standard.yml
      service: java-8-base
    image: 'prestodb/centos6-oj8-openldap:${DOCKER_IMAGES_VERSION}'
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh multinode-tls-ldap-worker run
    extra_hosts:
       - "${LDAP_SERVER_HOST}:${LDAP_SERVER_IP}"
    networks:
      default:
        aliases:
         - presto-worker-1.docker.cluster
    depends_on:
      - presto-master
    volumes_from:
      - presto-master

  presto-worker-2:
    domainname: docker.cluster
    hostname: presto-worker-2
    extends:
      file: ../common/standard.yml
      service: java-8-base
    image: 'prestodb/centos6-oj8-openldap:${DOCKER_IMAGES_VERSION}'
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh multinode-tls-ldap-worker run
    extra_hosts:
       - "${LDAP_SERVER_HOST}:${LDAP_SERVER_IP}"
    networks:
      default:
        aliases:
         - presto-worker-2.docker.cluster
    depends_on:
      - presto-master
    volumes_from:
      - presto-master

  application-runner:
    image: 'prestodb/centos6-oj8-openldap:${DOCKER_IMAGES_VERSION}'
    environment:
      - TEMPTO_PROFILE_CONFIG_FILE=/docker/volumes/conf/tempto/tempto-configuration-for-docker-tls-ldap.yaml
      - CLI_ARGUMENTS=--server https://presto-master.docker.cluster:7778 --keystore-path /docker/volumes/conf/presto/etc/docker.cluster.jks --keystore-password 123456 --user admin -P admin
